### PR TITLE
Update Apache Commons Collections from v3 to v4

### PR DESCRIPTION
**Pull request by soc**
This is done to allow users depending on JasperReports to get rid of their Collections v3 dependency, which hasn't been maintained for a few years now.

Please let me know if there are further changes necessary (I couldn't get it to build/test because it failed to resolve some of JasperReports' dependency, so any hints are appreciated).

### CODE REVIEW

**Comment by soc** [comment]
It's probably the best the view the changes without whitespace, not sure what happened there: https://github.com/TIBCOSoftware/jasperreports/pull/47/files?w=1

**Comment by teodord** [comment]
This is not as easy as it seems. Although we can get rid of Commons Collections v3 in the source code of JasperReports Library itself, we still depend on other third party libraries that need it.
For example, we parse JRXML report templates using Digester, which uses Commons BeanUtils, which uses Commons Collections v3. They are all old dependencies nowadays, but would be hard work to replace them.

**Comment by teodord** [comment]
We have upgraded JasperReports Library source code to Commons Collections 4 in the master branch. However, JRL still depends transiently upon Commons Collections 3 through Commons BeanUtils and Commons Digester.

**Comment by soc** [comment]
@teodord Thanks for the reply!

> JRL still depends transiently upon Commons Collections 3 through Commons BeanUtils ...

I inquired about the release of Bean Utils 2 (which uses Commons Collections 4) a while ago: http://mail-archives.apache.org/mod_mbox/commons-dev/201807.mbox/browser

I'll ping the maintainer again and find out what's still missing before a release can be made.

> ... and Commons Digester.

I have currently no information on that, but I'll try to figure out what can be done here.

Is there anything else that would block JRL from dropping Commons Collections 3?

Thanks,

Simon

**Pull request closed without merging**
