### PR TITLE
Fix issue-17, iText 2.1.7 to OpenPDF 1.3.11

### PR DESCRIPTION
**Pull request by srbala**
Resolves issue #17, replaces outdated and partial PR #29.

### CODE REVIEW

**Comment by srbala** [comment]
This also related to https://github.com/LibrePDF/OpenPDF/issues/145, solves JasperReport support

**Comment by ozawa-hi** [comment]
Can you provide a binary distribution of JasperReports library with OpenPDF? I still can't compile JasperReports with the changes you've provided.

**Comment by andreasrosdal** [comment]
@ozawa-hi Please share the compilation error that you get.

@srbala Can you please update this PR to the latest version of OpenPDF, which is 1.2.15 now?

**Comment by ozawa-hi** [comment]
Sorry my bad. Got it to build. Thanks.

**Comment by ozawa-hi** [comment]
I think TIBCO Jaspersoft is sticking with itext2.1.7 because of reasons written in the following page.
https://community.jaspersoft.com/wiki/issue-concerning-itext-licensing-tibco-jaspersoft

**Comment by shamimOnGitHub** [comment]
Hi ozawa-hi,

Were you able to run JasperReports using OpenPDF. How did you compile?

**Comment by andreasrosdal** [comment]
Any news on this? The latest version of OpenPDF is now 1.3.11. Maybe this pull request could be updated?

@ozawa-hi All the issues mentioned on that page are now addressed by OpenPDF. We have done a code review and resolved all questions related to licensing.
 More info here: https://github.com/LibrePDF/OpenPDF/wiki/OpenPDF---License-MPL---LGPL-background-info

**Comment by douph1** [comment]
Hi @teodord,

you have closed https://github.com/TIBCOSoftware/jasperreports/issues/17

>When the situation will change in the future, we'll reconsider.

but you reference this PR #53 in https://github.com/TIBCOSoftware/jasperreports/pull/29

Does it mean that there is a reconsideration ?
If not, why not close all PR ( and not just duplicate) about openpdf dependencies as wont-fix ?

**Comment by teodord** [comment]
We'll probably keep only one of these items open for the foreseeable future, as we cannot completely exclude that one day will make the switch.

**Comment by srbala** [comment]
@andreasrosdal updated OpenPDF to 1.3.11
@teodord resolved merge conflicts, this pull is ready for merge

**Comment by paksboda** [comment]
@teodord
Do we have plan to merge this anytime soon? We are using JasperReport and we want to migrate to OpenPDF. This is what we exactly need.

**Comment by teodord** [comment]
My understanding is that you can put OpenPDF in your application classpath instead of iText and it should work just fine.
If you look at the proposed changes, none are about Java source code modifications and are only about JAR references.
So you can do what you need to do without JasperReports project actually making any change itself.

**Comment by paksboda** [comment]
Thanks for response.
I agree with you and if not merged then I will do the same thing but if merge is happening anytime soon then it will be more cleaner implementation so I thought to confirm once.

**Comment by OleksandrShkurat** [comment]
Looks like this PR is outdated

**Comment by teodord** [comment]
A fork of OpenPDF 1.3.30 is going to be used in the next JasperReports Library release.

**Comment by OleksandrShkurat** [comment]
> A fork of OpenPDF 1.3.30 is going to be used in the next JasperReports Library release.

That's why I said this PR is outdated. I'd ssuggest closing it

**Comment by dadza** [comment]
Closing, iText has been replaces with a OpenPDF 1.3.30 patched dependency.

**Comment by soc** [comment]
@teodord Is there any information available on the differences of the forked OpenPDF vs. mainline OpenPDF? (Are there any compatibility concerns when replacing the forked one with the mainline one locally?)

**Comment by dadza** [comment]
The only difference is that our forked version includes a fix for https://github.com/LibrePDF/OpenPDF/issues/676

You can use the official OpenPDF 1.3.30 release if you don't mind the effects of that bug.

**Comment by soc** [comment]
@dadza Thank you!

**Pull request closed without merging**
